
server:
  port: 9999

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          dataSource:
            myDS:
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
              user: root
              password: 123456
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            dataSource: myDS
            isClustered: true

